# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb7d1ccc88cbae54308097c8ee041a6cd3cca66ad6034ec54a26209b371237e52633b9d41928b1b9df97b008cbca12c4911b19f883d3568c561361e9b8ed605

test:
  secret_key_base: e003abcb8aad1abc26f710edc71066ebff055d2d2e80bb5d5b592777c30e649412c6f138925bcc132e55febabab020f7c93abac0fc21d83749283f657d8eece1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
